name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ACR Build
        id: acr
        uses: ams0/acr-task-github-action@v2
        with:
          service_principal: ${{ secrets.ACR_USERNAME }}
          service_principal_password: ${{ secrets.ACR_PASSWORD }}
          registry: pluralsightdemoacr
          repository: gitopsdockerdeploy
          folder: ./DockerDeployDemo/
          dockerfile: DockerDeployDemo/Dockerfile
